# Generated by Django 6.0.3 on 2026-04-01 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
        ('exams', '0002_exam_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departement.departement'),
        ),
    ]
