# Generated by Django 6.0.3 on 2026-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examresult_created_at_alter_examresult_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_Finished',
            field=models.BooleanField(default=False),
        ),
    ]
