# Generated by Django 6.0.3 on 2026-03-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='mVWscHWlucgpSX5mlUL1alt0r92dp2dd', editable=False, max_length=32, unique=True),
        ),
    ]
