# Generated by Django 6.0.3 on 2026-03-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='0TVTnKiXeL8JSmjdLit0hFHOEewn9cVc', editable=False, max_length=32, unique=True),
        ),
    ]
