# Generated by Django 6.0.3 on 2026-03-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='1RcgKiHl2FeAMIpxtQ0Z06vpWf8HGMzT', editable=False, max_length=32, unique=True),
        ),
    ]
