# Generated by Django 6.0.3 on 2026-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='9QM3N4Cby1IHWqeitaCA3o9cL2wQ3uI8', editable=False, max_length=32, unique=True),
        ),
    ]
