# Generated by Django 6.0.3 on 2026-03-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='bh3ruTFxciWt07XgcVXEjWoE1mtNi7Ac', editable=False, max_length=32, unique=True),
        ),
    ]
