# Generated by Django 6.0.3 on 2026-03-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ap9cXeoMg78Mi5RXBLa30RCvoK0Iu9VL', editable=False, max_length=32, unique=True),
        ),
    ]
