# Generated by Django 6.0.3 on 2026-03-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='1Wzs63LvPa3nToeblpm7GGmVf13Yxx76', editable=False, max_length=32, unique=True),
        ),
    ]
