# Generated by Django 6.0.3 on 2026-04-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0010_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
