# Generated by Django 6.0.3 on 2026-04-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0013_remove_customuser_user_id_customuser_student_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
