# Generated by Django 6.0.3 on 2026-04-01 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0014_rename_student_id_customuser_student_and_more'),
        ('student', '0003_alter_student_student_id'),
        ('teacher', '0004_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentUser', to='student.student'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherUser', to='teacher.teacher'),
        ),
    ]
